name: OrangeFreedomMod
main: me.orangefreedom.orangefreedommod.OrangeFreedomMod
version: ${tfm.build.version}
description: Plugin for the Orange Freedom server.
depend: [Aero, WorldEdit]
softdepend: [BukkitTelnet, Essentials, LibsDisguises]
authors: [Madgeek1450, Prozza]

# plugin.yml is no longer used to define commands.
